import type { Metadata } from "next";
import { Outfit, Mulish, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/lib/auth/UserContext";
import { RoleSelectionDialog } from "@/components/auth/RoleSelectionDialog";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Climate Contribution Framework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${mulish.variable} ${jakarta.variable} antialiased`}
      >
        <UserProvider>
          <RoleSelectionDialog />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
