import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "@/lib/auth/UserContext";
import { RoleSelectionDialog } from "@/components/auth/RoleSelectionDialog";

const maisonNeue = localFont({
  src: [
    { path: "../public/fonts/Maison_Neue_Light.ttf", weight: "300" },
    { path: "../public/fonts/Maison_Neue_Book.ttf", weight: "400" },
    { path: "../public/fonts/Maison_Neue_Bold.ttf", weight: "700" },
  ],
  variable: "--font-maison",
});

const maisonNeueMono = localFont({
  src: [{ path: "../public/fonts/Maison_Neue_Mono.ttf", weight: "400" }],
  variable: "--font-maison-mono",
});

export const metadata: Metadata = {
  title: "Climate Contribution Framework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${maisonNeue.variable} ${maisonNeueMono.variable} antialiased`}
      >
        <UserProvider>
          <RoleSelectionDialog />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
